baseURL = "/ideal-octo-guacamole"

[menu]

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "resume"
    name = "Resume"
    url = "/resume"
    weight = 2

  [[menu.main]]
    identifier = "archives"
    name = "Archives"
    url = "/posts"
    weight = 3

[params]
  prismjsTheme = "okaidia"