languageCode = "en-us"
title = "ideal-octo-guacamole"
theme = ["github.com/sujithq/ideal-octo-guacamole"]
resourceDir = "../resources"
baseURL = "http://localhost:1313/"
 
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  categories = 'categories'
  tags = 'tags'
  series = 'series'

[menu]

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "resume"
    name = "Resume"
    url = "/resume"
    weight = 2

  [[menu.main]]
    identifier = "docs"
    name = "Documentation"
#     url = "/docs/"
    weight = 3

  [[menu.main]]
    identifier = "alerts"
    name = "Alerts"
    url = "/doc/alerts"
    weight = 1
    parent = "docs"

  [[menu.main]]
    identifier = "badges"
    name = "Badges"
    url = "/doc/badges"
    weight = 2
    parent = "docs"

  [[menu.main]]
    identifier = "taxonomy"
    name = "Taxonomy"
#     url = "/docs/"
    weight = 3

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags"
    weight = 1
    parent = "taxonomy"

  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories"
    weight = 2
    parent = "taxonomy"  

  [[menu.main]]
    identifier = "series"
    name = "Series"
    url = "/series"
    weight = 3
    parent = "taxonomy"  