baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "ideal-octo-guacamole"
theme = ["github.com/sujithq/ideal-octo-guacamole"]
resourceDir = "../resources"

[menu]

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "resume"
    name = "Resume"
    url = "/resume"
    weight = 2

  [[menu.main]]
    identifier = "docs"
    name = "Documentation"
#     url = "/docs/"
    weight = 3

  [[menu.main]]
    identifier = "alerts"
    name = "Alerts"
    url = "/doc/alerts"
    weight = 1
    parent = "docs"

  [[menu.main]]
    identifier = "badges"
    name = "Badges"
    url = "/doc/badges"
    weight = 2
    parent = "docs"

  [[menu.main]]
    identifier = "taxonomy"
    name = "Taxonomy"
#     url = "/docs/"
    weight = 3

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags"
    weight = 1
    parent = "taxonomy"

  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories"
    weight = 2
    parent = "taxonomy"  

  [[menu.main]]
    identifier = "series"
    name = "Series"
    url = "/series"
    weight = 3
    parent = "taxonomy"  
    
[params]
  theme = "forest"
  themes = ["dark", "light", "neon", "forest"]
  dateFormat = "Jan 2, 2006"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  categories = 'categories'
  tags = 'tags'
  series = 'series'

  [[params.socials]]
    name = "twitter"
    url = "https://x.com/SujithQ"
    icon = "bi bi-twitter-x"

  [[params.socials]]
    name = "facebook"
    url = "https://www.facebook.com/sujith.quintelier"
    icon = "bi bi-facebook"

  [[params.socials]]
    name = "github"
    url = "https://github.com/sujithq"
    icon = "bi bi-github"

  [[params.socials]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/sujithquintelier/"
    icon = "bi bi-linkedin"