baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "ideal-octo-guacamole"
theme = ["github.com/sujithq/ideal-octo-guacamole"]
resourceDir = "../resources"

[[menu.main]]
  name = "About"
  url = "/about/"

[[menu.main]]
    name = "Bootstrap Showcase"
    url = "/bootstrap-showcase/"
    weight = 2

[params]
  theme = "neon"
  themes = ["dark", "light", "neon"]